# -*- mode:yaml; indent-tabs-mode: nil; -*-
---

name: build-and-test
on:
  workflow_call:
    # No attempt to enforce strong data types.
    inputs:
      php-version:
        description: 'The php version under which to test'
        type: string
        default: '8.1'
jobs:
  build-and-test-job:
    name: Test in PHP version ${{ inputs.php-version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Run test suite
        run: composer test
        