name: PHP Composer

on:
  push:
    branches: [ "patch-1" ]
  pull_request:
    branches: [ "patch-1" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: PHP Info
        run: php -info
      - name: Validate composer.json and composer.lock
        run: composer validate --strict
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Run test suite
        run: composer run-script test